# Generated by Django 5.1.7 on 2025-04-01 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="birthdate",
            field=models.DateField(blank=True, null=True),
        ),
    ]
